Repository YaleSpinup/rds-api, pull requests merged in 2024-12, with the labels that each got.

#79 Added missing items to docker.local
  .github/workflows/test.yaml
  docker/Dockerfile.local
  go.mod
  go.sum
Labels: bug

#78 Support Serverless V2
  actions/orchestration.go
  actions/types.go
Labels: bug, enhancement

#81 Update go.mod and packages to be compatible with go1.23.4. Updated Dockerfile and Dockerfile.local
  docker/Dockerfile
  docker/Dockerfile.local
  go.mod
  go.sum
Labels: enhancement
